#buttons for MainWindow

<Button>:         #for all buttons
    size:         100, 50
    color:        1, 0, 0, 1 #red
    font_size:    20
    orientation:  'vertical'
    size_hint:    0.5, 0.5



<MainWindow>:

    Button:
        pos:       250, 200
        text:      'BUTTON1'


    Button:
        pos:       250, 150
        text:      'BUTTON2'


    Button:
        pos:      250, 100
        text:     'BUTTON3'
